import os
import certifi
from flask import Flask, request, jsonify
from flask_cors import CORS
from pymongo import MongoClient
from pymongo.errors import ConnectionFailure
from dotenv import load_dotenv
from bson.objectid import ObjectId
# pip install flask flask-cors pymongo python-dotenv certifi

load_dotenv()

app = Flask(__name__)
CORS(app)

mongo_uri = os.getenv("MONGO_URI")

client = MongoClient(mongo_uri, tlsCAFile=certifi.where())

try:
    client.admin.command('ping')
    print("✅ Successfully connected to MongoDB!")
except ConnectionFailure:
    print("❌ Failed to connect to MongoDB. Check your connection string.")

# Select the database and collection
db_users = client['kanban']
user_collection = db_users['user']
todolist_collection = db_users['todolist']


# --- ROUTES ---

@app.route('/signup', methods=['POST'])
def signup():
    """Register a new user and save them to MongoDB."""
    data = request.get_json()

    # 1. Validate that all required fields are present
    if not data or not data.get('username') or not data.get('email') or not data.get('password'):
        return jsonify({'error': 'Missing required fields (username, email, password)'}), 400

    # 2. Check if a user with this email already exists
    if user_collection.find_one({'email': data['email']}):
        return jsonify({'error': 'User with this email already exists'}), 409

    # 3. Create the user object (using plain text password for mock project)
    new_user = {
        'username': data['username'],
        'email': data['email'],
        'password': data['password']  # <--- Plain string stored here
    }

    # 4. Insert into database
    result = user_collection.insert_one(new_user)
    
    # 5. Prepare the userInfo object to send back to the frontend (excluding password)
    user_info = {
        'id': str(result.inserted_id),
        'username': new_user['username'],
        'email': new_user['email']
    }

    return jsonify({"message": "User created successfully", "userInfo": user_info}), 201


@app.route('/login', methods=['POST'])
def login():
    """Authenticate a user and return their info to the frontend."""
    data = request.get_json()
    # print(data, 'data received from frontend')  # Debugging statement
    # print(data.get('email'))
    
    # 1. Validate request payload
    if not data or not data.get('email') or not data.get('password'):
        return jsonify({'error': 'Missing email or password'}), 400

    # 2. Find the user by their email in MongoDB
    user = user_collection.find_one({'email': data['email']})

    # 3. Validate user exists AND the plain text passwords match
    if user and user['password'] == data['password']:  # <--- Plain string comparison here
        
        # 4. Prepare the userInfo object to send to the frontend
        # Even in a mock project, it's good practice not to send the password back!
        user_info = {
            'id': str(user['_id']),
            'username': user['username'],
            'email': user['email']
        }
        
        return jsonify({
            "message": "Login successful", 
            "userInfo": user_info
        }), 200
    else:
        return jsonify({"error": "Invalid email or password"}), 401




# 3. POST /board: Add a new board
# dashboard id is generated by MongoDB when we create a new document in the todolist collection.

@app.route('/board', methods=['POST'])
def create_board():
    data = request.get_json()
    user_id = data.get('userId')
    board_name = data.get('boardName')
    dashboard_id = data.get('dashboardId') # <-- New: Optional target dashboard

    if not user_id or not board_name:
        return jsonify({"error": "userId and boardName are required"}), 400

    try:
        user_oid = ObjectId(user_id) # Defining user_oid properly
        
        new_board = {
            "_id": ObjectId(),
            "boardName": board_name,
            "columns": []
        }
        
        if dashboard_id:
            # SCENARIO A: Targeting a specific dashboard (Member or Owner)
            dashboard_oid = ObjectId(dashboard_id)
            
            # Query: Must match the exact dashboard ID AND the user must be the owner OR a member
            query = {
                "_id": dashboard_oid,
                "$or": [
                    {"userId": user_oid},
                    {"member": user_oid}
                ]
            }
            # We set upsert=False here. If the shared dashboard doesn't exist, we shouldn't create a fake one.
            allow_upsert = False 
            
        else:
            # SCENARIO B: No dashboardId provided. Assume user's personal default dashboard.
            # Query: Just look for the user's own document
            query = {"userId": user_oid}
            # We set upsert=True here. If the user doesn't have a personal document yet, create one.
            allow_upsert = True

        result = todolist_collection.update_one(
            query,
            {
                "$push": {"todos": new_board},
                "$setOnInsert": {"member": []} 
            },
            upsert=allow_upsert
        )
        
        # If we targeted a specific dashboard but nothing matched, it means bad ID or no permissions
        if dashboard_id and result.matched_count == 0:
            return jsonify({"error": "Dashboard not found or you lack permission to add boards here"}), 403

        return jsonify({
            "message": "Board created successfully", 
            "boardId": str(new_board["_id"])
        }), 201

    except Exception as e:
        # Good practice to print the actual error to your console for debugging
        print(f"Error creating board: {e}") 
        return jsonify({"error": "Invalid ID format or database error"}), 400
    

# 2. POST /user/invite: Invite users to a board


# 4. GET /board: Get boards where user is owner OR a member
@app.route('/board', methods=['GET'])
def get_boards():
    user_id = request.args.get('userId')
    # print(user_id, 'userId received from frontend')  # Debugging statement
    
    if not user_id:
        return jsonify({"error": "userId query parameter is required"}), 400

    try:
        # $or operator: Find if user is the owner (userId) OR if user is in the member array
        query = {
            "$or": [
                {"userId": ObjectId(user_id)},
                {"member": ObjectId(user_id)}
            ]
        }
        dashboards = list(todolist_collection.find(query))
        # print(dashboards, 'dashboards found for user')  # Debugging statement
        # Deep conversion of ObjectIds to strings for the frontend
        for dash in dashboards:
            dash['_id'] = str(dash['_id'])
            dash['userId'] = str(dash['userId'])
            dash['member'] = [str(m) for m in dash.get('member', [])]
            
            for todo in dash.get('todos', []):
                todo['_id'] = str(todo['_id'])
                for col in todo.get('columns', []):
                    col['_id'] = str(col['_id'])
                    for task in col.get('tasks', []):
                        task['_id'] = str(task['_id'])
                        task['assignee'] = str(task.get('assignee', ''))  # Convert assignee to string, handle if it's missing
        return jsonify(dashboards), 200
    except Exception:
        return jsonify({"error": "Invalid userId format"}), 400


# 5. PUT /board: Update a board's name
@app.route('/board', methods=['PUT'])
def update_board():
    data = request.get_json()
    dashboard_id = data.get('dashboardId')
    board_id = data.get('boardId')
    new_name = data.get('newValueOfBoardName')

    if not all([dashboard_id, board_id, new_name]):
        return jsonify({"error": "dashboardId, boardId, and newValueOfBoardName are required"}), 400

    try:
        result = todolist_collection.update_one(
            {"_id": ObjectId(dashboard_id), 
             "todos._id": ObjectId(board_id)},
            {"$set": {"todos.$.boardName": new_name}}
        )
        
        # Check if the board was actually found
        if result.matched_count == 0:
            return jsonify({"error": "Dashboard or Board not found"}), 404
            
        return jsonify({"message": "Board updated successfully"}), 200
    except Exception:
        return jsonify({"error": "Invalid ID format"}), 400

# 6. DELETE /board: Delete multiple boards by ID (Owner only)
@app.route('/board', methods=['DELETE'])
def delete_boards():
    data = request.get_json()
    user_id = data.get('userId')           # <--- Added userId requirement
    dashboard_id = data.get('dashboardId')
    board_ids = data.get('boardId', [])    # Expects a list of string IDs

    # Validate all 3 fields exist
    if not user_id or not dashboard_id or not board_ids:
         return jsonify({"error": "userId, dashboardId, and boardId list are required"}), 400

    try:
        board_object_ids = [ObjectId(b_id) for b_id in board_ids]
        
        # Security fix: Match BOTH the dashboard's _id AND the owner's userId
        result = todolist_collection.update_one(
            {"_id": ObjectId(dashboard_id), "userId": ObjectId(user_id)},
            {"$pull": {"todos": {"_id": {"$in": board_object_ids}}}}
        )
        
        # If matched_count is 0, the dashboard either doesn't exist OR the user isn't the owner
        if result.matched_count == 0:
            return jsonify({"error": "Dashboard not found or you are not authorized to delete from it"}), 403
            
        return jsonify({"message": "Boards deleted successfully"}), 200
        
    except Exception:
         return jsonify({"error": "Invalid ID format"}), 400



@app.route('/board/column', methods=['POST'])
def create_column(): 
    # {, userId, dashboardId, boardId, columnName}
    data = request.get_json()
    user_id = data.get('userId')  # <--- Changed to userId
    dashboard_id = data.get('dashboardId') # need to pass dashboardId to find where column are pushed / spliced
    board_id = data.get('boardId')
    column_name = data.get('columnName')

    if not user_id or not dashboard_id or not board_id or not column_name:
        return jsonify({"error": "userId, dashboardId, boardId, and columnName are required"}), 400

    try:
        new_column = {
            "_id": ObjectId(), # Generate a new unique ID for this board
            "columnName": column_name,
            "tasks": [] # Initialize with empty columns
        }


        
        
        todolist_collection.update_one(
            {"userId": ObjectId(user_id), "_id": ObjectId(dashboard_id), "todos._id": ObjectId(board_id)},
            {
                "$push": {"todos.$.columns": new_column}
            },
          
        )
        
        return jsonify({
            "message": "Column created successfully", 
            "columnId": str(new_column["_id"])
        }), 201
    except Exception:
        return jsonify({"error": "Invalid userId format"}), 400


@app.route('/board/task', methods=['POST'])
def create_task():
    # {, userId, dashboardId, boardId, columnId, taskName}
    data = request.get_json()
    user_id = data.get('userId')  # <--- Changed to userId
    dashboard_id = data.get('dashboardId')
    board_id = data.get('boardId')
    column_id = data.get('columnId')
    task_name = data.get('taskName')
    if not user_id or not dashboard_id or not board_id or not column_id or not task_name:
        return jsonify({"error": "userId, dashboardId, boardId, columnId, and taskName are required"}), 400

    try:
        new_task = {
            "_id": ObjectId(), # Generate a new unique ID for this task
            "taskName": task_name,
            "assignee":""
        }
        
        todolist_collection.update_one(
            {"userId": ObjectId(user_id), "_id": ObjectId(dashboard_id), "todos._id": ObjectId(board_id), "todos.columns._id": ObjectId(column_id)},
            {
                # Use named placeholders: $[board] and $[col]
                "$push": {"todos.$[board].columns.$[col].tasks": new_task}
            },
            array_filters=[
                {"board._id": ObjectId(board_id)},
                {"col._id": ObjectId(column_id)}
            ]
        )
        
        return jsonify({
            "message": "Task created successfully", 
            "taskId": str(new_task["_id"])
        }), 201
    except Exception:
        return jsonify({"error": "Invalid userId format"}), 400


@app.route('/board/column', methods=['PUT'])
def update_column():
    data = request.get_json()
    dashboard_id = data.get('dashboardId')
    board_id = data.get('boardId')
    column_id = data.get('columnId')
    new_name = data.get('newValueOfColumnName')

    if not all([dashboard_id, board_id, column_id, new_name]):
        return jsonify({"error": "dashboardId, boardId, columnId, and newValueOfColumnName are required"}), 400

    try:
        result = todolist_collection.update_one(
            {
                "_id": ObjectId(dashboard_id),
                "todos._id": ObjectId(board_id),
                "todos.columns._id": ObjectId(column_id)
            },
            {
                "$set": {"todos.$[board].columns.$[col].columnName": new_name}
            },
            array_filters=[
                {"board._id": ObjectId(board_id)},
                {"col._id": ObjectId(column_id)}
            ]
        )
        # print(result.raw_result, 'update result')  # Debugging statement
        # Check if the board AND column were found
        if result.matched_count == 0:
            return jsonify({"error": "Dashboard, Board, or Column not found"}), 404
            
        return jsonify({"message": "Column updated successfully"}), 200
    except Exception:
        return jsonify({"error": "Invalid ID format"}), 400
    

@app.route('/board/task', methods=['PUT'])
def update_task():
    data = request.get_json()
    dashboard_id = data.get('dashboardId')
    board_id = data.get('boardId')
    column_id = data.get('columnId')
    task_id = data.get('taskId')
    new_name = data.get('newValueOfTaskName')

    if not all([dashboard_id, board_id, column_id, task_id, new_name]):
        return jsonify({"error": "dashboardId, boardId, columnId, taskId, and newValueOfTaskName are required"}), 400

    try:
        
        
        result = todolist_collection.update_one(
            {
                "_id": ObjectId(dashboard_id),
                "todos._id": ObjectId(board_id),
                "todos.columns._id": ObjectId(column_id),
                "todos.columns.tasks._id": ObjectId(task_id)
            },
            {
                "$set": {"todos.$[board].columns.$[col].tasks.$[task].taskName": new_name}
            },
            array_filters=[
                {"board._id": ObjectId(board_id)},
                {"col._id": ObjectId(column_id)},
                {"task._id": ObjectId(task_id)}
            ]
        )
        
        # print(result.matched_count, 'update result')  # Debugging statement
        # Check if the board, column, AND task were found
        if result.matched_count == 0:
            return jsonify({"error": "Dashboard, Board, Column, or Task not found"}), 404
            
        return jsonify({"message": "Task updated successfully"}), 200
    except Exception:
        return jsonify({"error": "Invalid ID format"}), 400

@app.route('/board/column', methods=['DELETE'])
def delete_column():
    data = request.get_json()
    user_id = data.get('userId')           # <--- Added userId requirement
    dashboard_id = data.get('dashboardId')
    board_id = data.get('boardId')
    column_ids = data.get('columnId', [])    # Expects a list of string IDs

    # Validate all 3 fields exist
    if not user_id or not dashboard_id or not column_ids:
         return jsonify({"error": "userId, dashboardId, and columnId list are required"}), 400

    try:
        column_object_ids = [ObjectId(c_id) for c_id in column_ids]
        
        # print(column_object_ids, 'column ids to delete')  # Debugging statement
        # Security fix: Match BOTH the dashboard's _id AND the owner's userId
        result = todolist_collection.update_one(
            {"_id": ObjectId(dashboard_id), "userId": ObjectId(user_id)},
            {
                # $pull from the specific board's columns array
                "$pull": {
                    "todos.$[board].columns": {"_id": {"$in": column_object_ids}}
                }
            },
            # Tell MongoDB which board to look inside
            array_filters=[
                {"board._id": ObjectId(board_id)}
            ]
        )
        
        # If matched_count is 0, the dashboard either doesn't exist OR the user isn't the owner
        if result.matched_count == 0:
            return jsonify({"error": "Dashboard not found or you are not authorized to delete from it"}), 403
            
        return jsonify({"message": "Column deleted successfully"}), 200
        
    except Exception:
         return jsonify({"error": "Invalid ID format"}), 400


@app.route('/board/task', methods=['DELETE'])
def delete_task():
    data = request.get_json()
    user_id = data.get('userId')           # <--- Added userId requirement
    dashboard_id = data.get('dashboardId')
    column_id = data.get('columnId')
    task_ids = data.get('taskId', []) # Expects a list of string IDs

    # Validate all 3 fields exist
    if not user_id or not dashboard_id or not column_id:
         return jsonify({"error": "userId, dashboardId, and columnId are required"}), 400

    try:
        task_object_ids = [ObjectId(t_id) for t_id in task_ids]

        # Security fix: Match BOTH the dashboard's _id AND the owner's userId
        result = todolist_collection.update_one(
            {"_id": ObjectId(dashboard_id), "userId": ObjectId(user_id)},
            {
                # $pull from the specific column's tasks array
                "$pull": {
                    "todos.$[board].columns.$[col].tasks": {"_id": {"$in": task_object_ids}}
                }
            },
            # Tell MongoDB exactly which board AND which column to look inside
            array_filters=[
                {"board._id": ObjectId(board_id)},
                {"col._id": ObjectId(column_id)}
            ]
        )
        
        # If matched_count is 0, the dashboard either doesn't exist OR the user isn't the owner
        if result.matched_count == 0:
            return jsonify({"error": "Dashboard not found or you are not authorized to delete from it"}), 403
            
        return jsonify({"message": "Boards deleted successfully"}), 200
        
    except Exception:
         return jsonify({"error": "Invalid ID format"}), 400


# 1. GET /user: List all users EXCEPT the currently logged-in user
@app.route('/user', methods=['GET'])
def get_all_other_users():
    owner_id = request.args.get('ownerId')
    
    if not owner_id:
        return jsonify({"error": "ownerId query parameter is required"}), 400

    try:
        # Find all users where _id is NOT EQUAL ($ne) to the ownerId
        # {"password": 0} excludes the password field from the results
        users = list(user_collection.find({"_id": {"$ne": ObjectId(owner_id)}}, {"password": 0}))
        
        # Convert ObjectIds to string for JSON serialization
        for user in users:
            user['_id'] = str(user['_id'])
            
        return jsonify(users), 200
    except Exception:
        return jsonify({"error": "Invalid ownerId format"}), 400



@app.route('/user/invite', methods=['POST'])
def invite_user():
    data = request.get_json()
    owner_id = data.get('ownerId')
    member_ids = data.get('memberId', []) # Expects a list of string IDs
    
    if not owner_id or not member_ids:
        return jsonify({"error": "ownerId and memberId list are required"}), 400

    try:
        # Convert list of string IDs to list of ObjectIds
        member_object_ids = [ObjectId(m_id) for m_id in member_ids]
        
        # $addToSet with $each adds multiple members WITHOUT creating duplicates
        todolist_collection.update_one(
            {"userId": ObjectId(owner_id)},
            {"$addToSet": {"member": {"$each": member_object_ids}}}
        )
        
        # As requested, just return successfully message
        return jsonify({"message": "successfully"}), 200
    except Exception:
         return jsonify({"error": "Invalid ID format"}), 400



@app.route('/board/task/assign', methods=['PUT'])
def assign_task():
    data = request.get_json()
    dashboard_id = data.get('dashboardId')
    board_id = data.get('boardId')
    column_id = data.get('columnId')
    task_id = data.get('taskId')
    assignee_id = data.get('assigneeId') # The new user being assigned

    if not all([dashboard_id, board_id, column_id, task_id, assignee_id]):
        return jsonify({"error": "dashboardId, boardId, columnId, taskId, and assigneeId are required"}), 400

    try:
        result = todolist_collection.update_one(
            {
                "_id": ObjectId(dashboard_id),
                "todos._id": ObjectId(board_id),
                "todos.columns._id": ObjectId(column_id),
                "todos.columns.tasks._id": ObjectId(task_id)
            },
            {
                # Target the assignee field. Assuming assigneeId is stored as an ObjectId!
                "$set": {"todos.$[board].columns.$[col].tasks.$[task].assignee": ObjectId(assignee_id)}
            },
            array_filters=[
                {"board._id": ObjectId(board_id)},
                {"col._id": ObjectId(column_id)},
                {"task._id": ObjectId(task_id)}
            ]
        )
        
        if result.matched_count == 0:
            return jsonify({"error": "Dashboard, Board, Column, or Task not found"}), 404
            
        return jsonify({"message": "Task assigned successfully"}), 200
    except Exception:
        return jsonify({"error": "Invalid ID format"}), 400
    
    
    
@app.route('/board/task/move', methods=['PUT'])
def move_task():
    data = request.get_json()
    dashboard_id = data.get('dashboardId')
    task_id = data.get('taskId')
    old_board_id = data.get('oldBoardId')
    old_column_id = data.get('oldColumnId')
    new_board_id = data.get('newBoardId')
    new_column_id = data.get('newColumnId')
    new_index = data.get('newIndex') # We DO need this!

    if new_index is None: # Explicitly check None because index could be 0
        return jsonify({"error": "Missing required fields"}), 400

    try:
        dash_oid = ObjectId(dashboard_id)
        task_oid = ObjectId(task_id)

       # STEP 1: READ the task data using an Aggregation Pipeline
        dash_oid = ObjectId(dashboard_id)
        task_oid = ObjectId(task_id)

        pipeline = [
            # 1. Find the specific dashboard
            {"$match": {"_id": dash_oid}},
            
            # 2. Deconstruct the 'todos' (boards) array
            {"$unwind": "$todos"},
            # Match the specific board
            {"$match": {"todos._id": ObjectId(old_board_id)}},
            
            # 3. Deconstruct the 'columns' array
            {"$unwind": "$todos.columns"},
            # Match the specific column
            {"$match": {"todos.columns._id": ObjectId(old_column_id)}},
            
            # 4. Deconstruct the 'tasks' array
            {"$unwind": "$todos.columns.tasks"},
            # Match the exact task we want to move
            {"$match": {"todos.columns.tasks._id": task_oid}},
            
            # 5. Make the matched task the root object to return
            {"$replaceRoot": {"newRoot": "$todos.columns.tasks"}}
        ]

        result = list(todolist_collection.aggregate(pipeline))
        
        # If the list isn't empty, we found our task data
        task_data = result[0] if result else None

        if not task_data:
            return jsonify({"error": "Original task not found"}), 404

        # STEP 2: PULL (Remove) the task from its old location
        todolist_collection.update_one(
            {"_id": dash_oid},
            {
                "$pull": {"todos.$[board].columns.$[col].tasks": {"_id": task_oid}}
            },
            array_filters=[
                {"board._id": ObjectId(old_board_id)},
                {"col._id": ObjectId(old_column_id)}
            ]
        )

        # STEP 3: PUSH (Insert) the task into the new location at the specific index
        todolist_collection.update_one(
            {"_id": dash_oid}, # does not require check existence because it is move task
            {
                "$push": {
                    "todos.$[board].columns.$[col].tasks": {
                        "$each": [task_data],       # The data we copied in Step 1
                        "$position": int(new_index) # The exact slot to drop it into!
                    }
                }
            },
            array_filters=[
                {"board._id": ObjectId(new_board_id)},
                {"col._id": ObjectId(new_column_id)}
            ]
        )

        return jsonify({"message": "Task moved successfully"}), 200

    except Exception as e:
        return jsonify({"error": "Invalid data format or server error"}), 400
    

    
if __name__ == '__main__':
    # Run the Flask app on port 3000
    app.run(debug=True, port=3000)